CREATE TABLE automation_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_key VARCHAR(100) NOT NULL,
    job_type VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    timezone VARCHAR(64) NOT NULL,
    schedule_type VARCHAR(20) NOT NULL DEFAULT 'cron',
    cron_expression VARCHAR(100) NOT NULL,
    catch_up_policy VARCHAR(20) NOT NULL DEFAULT 'latest',
    overlap_policy VARCHAR(20) NOT NULL DEFAULT 'forbid',
    model_provider VARCHAR(100) NOT NULL,
    model_id VARCHAR(150) NOT NULL,
    model_parameters JSON NOT NULL,
    model_catalog_version VARCHAR(100) NULL,
    retry_max_attempts INT NOT NULL DEFAULT 3,
    retry_interval_seconds INT NOT NULL DEFAULT 300,
    timeout_seconds INT NOT NULL DEFAULT 2700,
    retention_days INT NOT NULL DEFAULT 90,
    last_scheduled_at DATETIME(6) NULL,
    last_started_at DATETIME(6) NULL,
    last_finished_at DATETIME(6) NULL,
    next_run_at DATETIME(6) NULL,
    last_run_status VARCHAR(32) NULL,
    configuration_status VARCHAR(20) NOT NULL DEFAULT 'unverified',
    configuration_error VARCHAR(500) NULL,
    version INT NOT NULL DEFAULT 1,
    created_by INT NULL,
    updated_by INT NULL,
    deleted_at DATETIME(6) NULL,
    deleted_by INT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_jobs_job_key (job_key),
    KEY idx_automation_jobs_due (enabled, next_run_at),
    KEY idx_automation_jobs_configuration (configuration_status),
    KEY idx_automation_jobs_model (model_provider, model_id),
    KEY idx_automation_jobs_deleted (deleted_at),
    CONSTRAINT chk_automation_jobs_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_automation_jobs_schedule_type CHECK (schedule_type = 'cron'),
    CONSTRAINT chk_automation_jobs_catch_up CHECK (catch_up_policy IN ('skip', 'latest')),
    CONSTRAINT chk_automation_jobs_overlap CHECK (overlap_policy = 'forbid'),
    CONSTRAINT chk_automation_jobs_configuration CHECK (configuration_status IN ('valid', 'invalid', 'unverified')),
    CONSTRAINT chk_automation_jobs_retry_attempts CHECK (retry_max_attempts BETWEEN 1 AND 10),
    CONSTRAINT chk_automation_jobs_retry_interval CHECK (retry_interval_seconds BETWEEN 0 AND 86400),
    CONSTRAINT chk_automation_jobs_timeout CHECK (timeout_seconds BETWEEN 60 AND 86400),
    CONSTRAINT chk_automation_jobs_retention CHECK (retention_days BETWEEN 1 AND 3650)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_tags (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    color VARCHAR(32) NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT NULL,
    updated_by INT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_tags_normalized_name (normalized_name),
    KEY idx_automation_tags_enabled_name (enabled, name),
    CONSTRAINT chk_automation_tags_enabled CHECK (enabled IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_job_tags (
    job_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (job_id, tag_id),
    UNIQUE KEY uq_automation_job_tags_job_tag (job_id, tag_id),
    KEY idx_automation_job_tags_tag_job (tag_id, job_id),
    CONSTRAINT fk_automation_job_tags_job FOREIGN KEY (job_id)
        REFERENCES automation_jobs (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_automation_job_tags_tag FOREIGN KEY (tag_id)
        REFERENCES automation_tags (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_prompt_profiles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_type VARCHAR(100) NOT NULL,
    system_prompt TEXT NOT NULL,
    prompt_version VARCHAR(100) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_prompt_profiles_job_type (job_type),
    CONSTRAINT chk_automation_prompt_profiles_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_automation_prompt_profiles_version CHECK (version >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_job_runs (
    id CHAR(36) NOT NULL,
    root_run_id CHAR(36) NOT NULL,
    parent_run_id CHAR(36) NULL,
    job_id BIGINT NOT NULL,
    job_key_snapshot VARCHAR(100) NOT NULL,
    job_name_snapshot VARCHAR(255) NOT NULL,
    job_type_snapshot VARCHAR(100) NOT NULL,
    description_snapshot TEXT NOT NULL,
    tags_snapshot JSON NOT NULL,
    trigger_source VARCHAR(20) NOT NULL,
    scheduled_at DATETIME(6) NOT NULL,
    available_at DATETIME(6) NOT NULL,
    triggered_at DATETIME(6) NOT NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    status VARCHAR(32) NOT NULL,
    attempt INT NOT NULL DEFAULT 1,
    model_provider_snapshot VARCHAR(100) NOT NULL,
    model_id_snapshot VARCHAR(150) NOT NULL,
    model_parameters_snapshot JSON NOT NULL,
    model_catalog_version_snapshot VARCHAR(100) NULL,
    prompt_version_snapshot VARCHAR(100) NULL,
    system_prompt_snapshot MEDIUMTEXT NULL,
    cron_expression_snapshot VARCHAR(100) NOT NULL,
    timezone_snapshot VARCHAR(64) NOT NULL,
    retry_max_attempts_snapshot INT NOT NULL,
    retry_interval_seconds_snapshot INT NOT NULL,
    timeout_seconds_snapshot INT NOT NULL,
    deadline_at DATETIME(6) NOT NULL,
    worker_instance VARCHAR(255) NULL,
    lease_token_digest CHAR(64) NULL,
    lease_duration_seconds INT NULL,
    lease_expires_at DATETIME(6) NULL,
    heartbeat_at DATETIME(6) NULL,
    projects_total INT NOT NULL DEFAULT 0,
    projects_succeeded INT NOT NULL DEFAULT 0,
    projects_failed INT NOT NULL DEFAULT 0,
    mutations_applied TINYINT(1) NOT NULL DEFAULT 0,
    retry_recommended TINYINT(1) NOT NULL DEFAULT 0,
    duration_ms BIGINT NULL,
    error_code VARCHAR(100) NULL,
    error_summary VARCHAR(1000) NULL,
    cancel_requested_at DATETIME(6) NULL,
    cancel_requested_by INT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_job_runs_schedule_attempt (job_id, scheduled_at, attempt),
    KEY idx_automation_job_runs_status_schedule (status, scheduled_at),
    KEY idx_automation_job_runs_pending (status, available_at),
    KEY idx_automation_job_runs_job_created (job_id, created_at),
    KEY idx_automation_job_runs_lease (lease_expires_at),
    KEY idx_automation_job_runs_root (root_run_id, attempt),
    CONSTRAINT fk_automation_job_runs_job FOREIGN KEY (job_id)
        REFERENCES automation_jobs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_automation_job_runs_root FOREIGN KEY (root_run_id)
        REFERENCES automation_job_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_automation_job_runs_parent FOREIGN KEY (parent_run_id)
        REFERENCES automation_job_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_automation_job_runs_trigger CHECK (trigger_source IN ('schedule', 'manual', 'retry', 'catch_up')),
    CONSTRAINT chk_automation_job_runs_status CHECK (status IN ('pending', 'claimed', 'running', 'succeeded', 'partial_failed', 'failed', 'configuration_error', 'skipped', 'cancelled')),
    CONSTRAINT chk_automation_job_runs_attempt CHECK (attempt >= 1),
    CONSTRAINT chk_automation_job_runs_lease_duration CHECK (lease_duration_seconds IS NULL OR lease_duration_seconds BETWEEN 60 AND 600)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_job_run_projects (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id CHAR(36) NOT NULL,
    project_id INT NOT NULL,
    project_name_snapshot VARCHAR(255) NOT NULL,
    status_before VARCHAR(32) NULL,
    status_after VARCHAR(32) NULL,
    outcome VARCHAR(50) NOT NULL,
    repository_count INT NOT NULL DEFAULT 0,
    commit_count INT NOT NULL DEFAULT 0,
    summary_date DATE NULL,
    source_digest VARCHAR(128) NULL,
    generated_summary LONGTEXT NULL,
    ai_confidence INT NULL,
    ai_note TEXT NULL,
    warnings JSON NOT NULL,
    mutations_applied TINYINT(1) NOT NULL DEFAULT 0,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    duration_ms BIGINT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_run_projects_run_project (run_id, project_id),
    KEY idx_automation_run_projects_project (project_id, created_at),
    KEY idx_automation_run_projects_outcome (outcome),
    CONSTRAINT fk_automation_run_projects_run FOREIGN KEY (run_id)
        REFERENCES automation_job_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_automation_run_projects_confidence CHECK (ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 100),
    CONSTRAINT chk_automation_run_projects_outcome CHECK (outcome IN ('evaluated', 'archived', 'no_github_urls', 'no_commits', 'invalid_github_urls', 'incomplete', 'write_conflict', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_ai_interactions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id CHAR(36) NOT NULL,
    run_project_id BIGINT NOT NULL,
    interaction_key VARCHAR(100) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model VARCHAR(150) NOT NULL,
    model_catalog_version VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    system_prompt_snapshot LONGTEXT NULL,
    request_payload_sanitized JSON NULL,
    response_payload_sanitized JSON NULL,
    final_summary LONGTEXT NULL,
    limitations JSON NOT NULL,
    fallback_used TINYINT(1) NOT NULL DEFAULT 0,
    upstream_request_id VARCHAR(255) NULL,
    input_tokens INT NULL,
    output_tokens INT NULL,
    latency_ms BIGINT NULL,
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(100) NULL,
    error_summary VARCHAR(1000) NULL,
    purged_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_ai_run_interaction (run_id, interaction_key),
    KEY idx_automation_ai_run (run_id, created_at),
    KEY idx_automation_ai_run_project (run_project_id),
    CONSTRAINT fk_automation_ai_run FOREIGN KEY (run_id)
        REFERENCES automation_job_runs (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_automation_ai_run_project FOREIGN KEY (run_project_id)
        REFERENCES automation_job_run_projects (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_job_change_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    version_before INT NULL,
    version_after INT NOT NULL,
    changes_json JSON NOT NULL,
    operated_by INT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_automation_job_change_logs_job (job_id, created_at),
    CONSTRAINT fk_automation_job_change_logs_job FOREIGN KEY (job_id)
        REFERENCES automation_jobs (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE automation_run_trace_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(36) NOT NULL,
    event_key VARCHAR(200) NOT NULL,
    sequence INT NOT NULL,
    phase VARCHAR(100) NOT NULL,
    status VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NULL,
    progress_current INT NULL,
    progress_total INT NULL,
    project_id BIGINT NULL,
    repository_full_name VARCHAR(255) NULL,
    metadata_sanitized JSON NOT NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_automation_trace_run_event (run_id, event_key),
    KEY idx_automation_trace_run_sequence (run_id, sequence, occurred_at, id),
    KEY idx_automation_trace_run_status (run_id, status),
    CONSTRAINT fk_automation_trace_run FOREIGN KEY (run_id)
        REFERENCES automation_job_runs (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
