INSERT INTO automation_jobs (
    job_key,
    job_type,
    name,
    description,
    enabled,
    timezone,
    schedule_type,
    trigger_type,
    trigger_config,
    cron_expression,
    catch_up_policy,
    overlap_policy,
    model_provider,
    model_id,
    model_parameters,
    model_catalog_version,
    retry_max_attempts,
    retry_interval_seconds,
    timeout_seconds,
    retention_days,
    next_run_at,
    configuration_status,
    configuration_error,
    version,
    created_by,
    updated_by,
    created_at,
    updated_at
) VALUES (
    'weekly-report-project-summary-sync',
    'weekly_report_project_summary_sync',
    '周报更新监控 → 项目总结同步',
    '监控周报新增或更新内容，按所有项目（含归档项目）拆分更新点，并写入项目总结接口。',
    0,
    'Asia/Shanghai',
    'event',
    'event',
    JSON_OBJECT(
        'resource', 'weekly_report',
        'events', JSON_ARRAY('created', 'updated'),
        'scope', 'job_owner'
    ),
    NULL,
    'latest',
    'forbid',
    'nexttoken',
    'gpt-5.6-terra',
    JSON_OBJECT(
        'project_scope', 'all_projects',
        'include_archived_projects', TRUE,
        'write_archived_projects', TRUE,
        'minimum_confidence', 0.8,
        'on_ambiguous', 'no_write',
        'debounce_seconds', 60
    ),
    NULL,
    3,
    300,
    2700,
    90,
    NULL,
    'unverified',
    '等待管理员连接 OAagent 后验证模型配置',
    1,
    NULL,
    NULL,
    UTC_TIMESTAMP(6),
    UTC_TIMESTAMP(6)
) ON DUPLICATE KEY UPDATE job_key = VALUES(job_key);
