import assert from "node:assert/strict";
import test from "node:test";

import {
  OaSessionError,
  verifyOaSession,
} from "../src/automation/auth/oaSession.js";

// Generated by Python:
// TimestampSigner("dummy").sign(base64.b64encode(b'{"user_id":42}'))
const PYTHON_SIGNED_SESSION =
  "eyJ1c2VyX2lkIjo0Mn0=.anrC2Q.pEFWxzjfMt0mY3AiF3rdGDgnmrk";

test("verifies an OA itsdangerous session and extracts user_id", () => {
  const session = verifyOaSession(PYTHON_SIGNED_SESSION, {
    secret: "dummy",
    maxAgeSeconds: 0,
    nowSeconds: 1_800_000_000,
  });

  assert.equal(session.userId, 42);
  assert.equal(session.payload.user_id, 42);
});

test("rejects a tampered OA session", () => {
  assert.throws(
    () =>
      verifyOaSession(`${PYTHON_SIGNED_SESSION}x`, {
        secret: "dummy",
        maxAgeSeconds: 0,
      }),
    (error: unknown) =>
      error instanceof OaSessionError && error.code === "invalid_session",
  );
});

test("enforces max age when OA_SESSION_VERIFY_MAX_AGE is positive", () => {
  assert.throws(
    () =>
      verifyOaSession(PYTHON_SIGNED_SESSION, {
        secret: "dummy",
        maxAgeSeconds: 60,
        nowSeconds: 1_800_000_000,
      }),
    (error: unknown) =>
      error instanceof OaSessionError && error.code === "expired_session",
  );
});

